# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9546c791b827a463551b2ea0baf5992f97b2b9c02ab2e3e73694d28ba7b3d8cba9fe35926865382dc48b9ad6b72b188fb50fbc409d9f9004420b0721090a520

test:
  secret_key_base: 9c31643b9845231eaf783e624b9d0138cee9a7e55c019c589568bde1693a259b1bc73c5ee855a8c89590b773c3a1aa64d70fde8f9ca48c9652b23050a7ce961a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
